name: test_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  pub_semver: ^2.1.4
  updat: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
